---
- name: Configure notes before anything else
  hosts: all
  
- hosts: all:!amos_glusterfs
  roles:
  #refactor me as Im doing way too much job!!! + none of this is indenpontent
   - rhel_register_node

- hosts: amos_glusterfs
  vars:
    redhat_satellite_fqdn: "{{ crs_redhat_satellite_fqdn }}"
    redhat_organization_id: "{{ crs_redhat_organization_id }}"
    redhat_activationkey: "{{ crs_redhat_activationkey }}"
  roles:
  #refactor me as Im doing way too much job!!! + none of this is indenpontent
   - rhel_register_node

- hosts: all:!bastion:!controller:!amos_glusterfs
  roles:
    - repos

- hosts: amos_glusterfs
  vars:
    repos_to_enable: "{{ gluster_repos  }}"
  roles:
    - repos

- hosts: all:!bastion:!controller
  roles:
  # this doing way too much, refactor me to smallers roles. + none of this is indenpontent
   - ocp_configure_node

- hosts: all:!bastion:!controller:!amos_glusterfs
  roles:
  # this doing way too much, refactor me to smallers roles. + none of this is indenpontent
   - docker
